typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=002 # Here! -> 76
typeset -g POWERLEVEL9K_DIR_FOREGROUND=012 # Here! -> 31
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=004 # Here! -> 39
local      clean='%002F'   # green foreground Here! -> 76
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR=002 # Here! -> 76
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=002 # Here! -> 76
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=002 # Here! -> 76




